export const BRANDS = [
  { key: "xiaomi", label: "Xiaomi", color: "#FF6900", logo: "/assets/brand/Mobile Brand Logos-01.png" },
  { key: "honor", label: "Honor", color: "#2F80ED", logo: "/assets/brand/Mobile Brand Logos-02.png" },
  { key: "infinix", label: "Infinix", color: "#16A34A", logo: "/assets/brand/Mobile Brand Logos-03.png" },
  { key: "realme", label: "Realme", color: "#EAB308", logo: "/assets/brand/Mobile Brand Logos-04.png" },
  { key: "tecno", label: "Tecno", color: "#7C3AED", logo: "/assets/brand/Mobile Brand Logos-05.png" },
  { key: "huawei", label: "Huawei", color: "#DC2626", logo: "/assets/brand/Mobile Brand Logos-06.png" },
];

export const stores = [
  {
    id: 1,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Cox's Bazar",
    thana: "Cox's Bazar",
    name: "Mi Store, Coxs Bazar (DTL)",
    address: "Shop no.01, 2nd Floor, Bilkis Shopping Complex, Cox's Bazar",
    contract: "01708464123",
  },
  {
    id: 2,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Cumilla",
    thana: "Cumilla Sadar",
    name: "Mi Store, SEBL 15, Comilla - 1",
    address: "C-502, 3rd Floor, Khondkar Haq Tower,Cumilla",
    contract: "01313027146",
  },
  {
    id: 3,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Feni",
    thana: "Feni Sadar",
    name: "Mi Store, SEBL 09, Feni",
    address: "Jail Road, Beside Zila Primary Education Office,Feni",
    contract: "01313027186",
  },
  {
    id: 4,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "EPZ Thana",
    name: "Mi Store Chittagong - EPZ-2 (DTL)",
    address:
      "Saleh Complex Ground Floor, Beside Sundarban Courier Service, Free Port Moor, Chattogram",
    contract: "01322877212",
  },
  {
    id: 5,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "Panchlaish Thana",
    name: "Mi Store Sanmar (DTL)",
    address: "shop#465,4th floor,Sanmar Ocean City , Chattogram",
    contract: "01730399140",
  },
  {
    id: 6,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chandpur",
    thana: "Hajiganj",
    name: "Mi Store, SEBL 24, Hajiganj, Chandpur,",
    address: "Shop#5-6,,shariar super market,west bazar,Hazigonj, chandpur",
    contract: "01708813760",
  },
  {
    id: 7,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "Bandar Thana",
    name: "Mi Store, Chittagong - EPZ (DTL)",
    address:
      "Ground floor, Islam Mansion,free port, Chittagong (Opposite of Barister College)",
    contract: "01708813740",
  },
  {
    id: 8,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "Double mooring",
    name: "Mi Store, Singapore Bangkok-1 (DTL)",
    address: "Shop#432,3rd floor,Singapore Bangkok Market ,Agrabad,Chittagong",
    contract: "01730399144",
  },
  {
    id: 9,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "Panchlaish Thana",
    name: "Mi Store (SEBL-23) Sanmar_Chittagong",
    address: "shop#448,4th floor,Sanmar Ocean City , Chattogram",
    contract: "01708464179",
  },
  {
    id: 10,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Cumilla",
    thana: "Cumilla Sadar",
    name: "Mi Store, Cumilla-5 (DTL)",
    address: "Shop No#21, Senakollan Market, Centonment, Cumilla",
    contract: "01322877282",
  },
  {
    id: 11,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "panchlaish thana",
    name: "Mi Store, Finlay Square (DTL)",
    address: "Shop-410, Level-5, Finlay Square, East Nasirabad, chittagong",
    contract: "01708813750",
  },
  {
    id: 12,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Chittagong",
    thana: "Lohagara",
    name: "Mi Store Lohagara (DTL)",
    address:
      "A Rahman Market, Under Krishi Bank, Amirabad, Lohagara, Chattogram",
    contract: "01313027183",
  },
  {
    id: 13,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Cumilla",
    thana: "Cumilla Sadar",
    name: "Mi Store, Rupayan Tower - DTL, Comilla",
    address: "Shop# 405, 3rd Floor, Rupayan Delwar Tower, Kandirpar, Cumilla",
    contract: "01730399126",
  },
  {
    id: 14,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Chattogram",
    district: "Cox's Bazar",
    thana: "Cox's Bazar",
    name: "Mi Store, Cox's Bazar (DTL)-2, Laldighir Par",
    address:
      "Shop No-01, Zilani Shoping Complex (Ground floor),Lal dighir par,Main Road,Cox's Bazar",
    contract: "01322877283",
  },
  {
    id: 15,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Vatara",
    name: "Mi Store, JFP-1 (DTL)",
    address:
      "Shop-18/C1- Block-C, Level-04,Jamuna Future Park ,basundhara,Dhaka",
    contract: "01708813768",
  },
  {
    id: 16,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Uttara",
    name: "Mi Store Uttara (North Tower)",
    address: "Shop-517,level-5th, North Tower Market, Uttara, Dhaka",
    contract: "01708813747",
  },
  {
    id: 17,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Manikganj",
    thana: "Manikganj Sodor",
    name: "Mi Store Manikgonj",
    address: "S#200/3,Shahid rafique Road Manikganj-1800",
    contract: "01708813726",
  },
  {
    id: 18,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Badda",
    name: "Mi Store Badda Link Road-2",
    address: "Shop : T-136/2 Badda link Road, Gulshan- Dhaka",
    contract: "01708813779",
  },
  {
    id: 19,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Gulshan",
    name: "Mi Store, Police Plaza (DTL)",
    address: "Shop no : 542, Level 4, Police Plaza, Gulshan-1.",
    contract: "01730399118",
  },
  {
    id: 20,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "mirpur Thana",
    name: "Mi Store Mirpur-02",
    address: "shop632/633 level-5 mirpur-2 shopping center",
    contract: "01708813728",
  },
  {
    id: 21,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Gazipur",
    thana: "Bashon",
    name: "Mi Store Anupom-1 (DTL)",
    address: "Shop #6 1st Floor, Anupom Super Market, Chowrasta, Gazipur.",
    contract: "01322877253",
  },
  {
    id: 22,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Gazipur",
    thana: "Sreepur",
    name: "Mi Store Mawna-1 (DTL)",
    address: "Shop no-2,Mawna,Sreepur,Gazipur",
    contract: "01322877255",
  },
  {
    id: 23,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Uttara",
    name: "Mi Store North Tower-2 (DTL)",
    address: "Shop-501,level-5th, North Tower Market, Uttara, Dhaka",
    contract: "01730399136",
  },
  {
    id: 24,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Vatara",
    name: "Mi Store, JFP-2 (DTL)",
    address: "SHOP-04/C, 020, B-2, LEVEL-04, JAMUNA FUTURE PARK",
    contract: "01730399133",
  },
  {
    id: 25,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Uttara",
    name: "Mi Store Center Point (DTL)",
    address: "Level-4, Shop-407, Center point, Air port Road, Dhaka.",
    contract: "01730399132",
  },
  {
    id: 26,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Vatara",
    name: "Mi Store JFP-3 (DTL)",
    address:
      "001 B1, Block-C, Level-4, Jamuna Future Park, pragati Sarani, Dhaka",
    contract: "01730399145",
  },
  {
    id: 27,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Sylhet",
    district: "Hobiganj",
    thana: "Hobiganj",
    name: "Mi Store Hobigang",
    address: "Hazi Mansion commercial area,Hobiganj",
    contract: "01708813786",
  },
  {
    id: 28,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Sylhet",
    district: "Moulvibazar",
    thana: "Moulvibazar",
    name: "Mi Store Moulvibazar",
    address: "SR Plaza,Saufur Rahman Road , Kusumbag , Moulvibazar",
    contract: "01708813776",
  },
  {
    id: 29,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Sylhet",
    district: "Moulvibazar",
    thana: "Moulvibazar Sadar",
    name: "Mi Store Moulavibazar-2 (DTL)",
    address: "Holding No-1, Sayed Rabyea Mension, Sylhet, Moulavibazar",
    contract: "01708813704",
  },
  {
    id: 30,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Mymensing",
    district: "Kishoreganj",
    thana: "Kishoreganj Sodor",
    name: "Mi Store Kishorgong",
    address: "148, Station Road, Puranthana, Kishoreganj",
    contract: "01708813774",
  },
  {
    id: 31,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "B. City Level-1, Shop- 5 & 6",
    address:
      "Shop-5&6, Basement 1, Bashundhara City Shopping Mall, Panthapath,Dhaka",
    contract: "01708464121",
  },
  {
    id: 32,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Dhanmondi",
    name: "Mi Store, Shimanto Square (DTL)",
    address: "Shop-341,3rd Floor,Shimanto Square complex ,Dhanmodi-2 Dhaka",
    contract: "01708813727",
  },
  {
    id: 33,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "Mi StoreB. City Level-1, Shop- 51",
    address: "Shop-51, Basement 1, Bashundhara City Shopping Mall, Dhaka",
    contract: "01708813725",
  },
  {
    id: 34,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Kolabagan",
    name: "Mi Store Eastern Plaza (Dhaka, DTL)",
    address: "Shop:5/12,Eastern Plaza, Hatirpool,Dhaka",
    contract: "01730399117",
  },
  {
    id: 35,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "Mi Store B. City Level-1, Shop- 19",
    address: "Bashundhara city, Basement 1. shop 19",
    contract: "01730399123",
  },
  {
    id: 36,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Narayangonj",
    thana: "#N/A",
    name: "Mi Store Narayangonj(DTL)",
    address: "123, Sufiya Plaza , BB Road ,Narayangonj",
    contract: "01708813746",
  },
  {
    id: 37,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Hatirpool",
    name: "Mi Store Motaleb Plaza (SEBL-25)",
    address: "Shopp #524,Level#4,Motaleb Plaza,Hatirpool,Dhaka",
    contract: "01713123971",
  },
  {
    id: 38,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Jatrabari",
    name: "Mi Store, SEBL 11, Jatrabari",
    address: "97, Shahid Faruq Road South Jatrabari, Dhaka -1204",
    contract: "01313027160",
  },
  {
    id: 39,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Demra",
    name: "Mi Store, DTL, Demra",
    address: "shop no 56,2nd floor hazi Hossain plaza",
    contract: "01708813724",
  },
  {
    id: 40,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Polton",
    name: "Mi Store, (Eastern Plus) (DTL)",
    address: "Level-5, Shop-42, Eastern Plus Market, Shantinagar",
    contract: "01708813730",
  },
  {
    id: 41,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Polton",
    name: "Mi Store, Fakirapool (DTL)",
    address: "32, Fakirapool, Naya Polton",
    contract: "01730399124",
  },
  {
    id: 42,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Motijheel",
    name: "Mi Store, Motijheel (DTL)",
    address: "109 motijheel C/A, Dhaka -1000",
    contract: "01730399122",
  },
  {
    id: 43,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Narsingdi",
    thana: "Sadar",
    name: "Mi Store, SEBL 12, Narshingdhi",
    address:
      "AK Bhabon Electronics Shoping Complex 23,west kandapara,Narsingdi",
    contract: "01313027156",
  },
  {
    id: 44,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Polton",
    name: "Mi Store, SEBL 3, Baitul View",
    address: "Shop#304,level-3 baitul view tower, puran paltan",
    contract: "01313027184",
  },
  {
    id: 45,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Lalbag",
    name: "Mi Store, Lalbag (DTL)",
    address: "60 Horonath Gosh Road, Lalbag, Dhaka-1211",
    contract: "01708464125",
  },
  {
    id: 46,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Tangail",
    thana: "Tangail Sadar",
    name: "Mi Store Tangail",
    address: "Bindu Bashini Girls School Road, Tangail",
    contract: "01708464126",
  },
  {
    id: 47,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Mymensing",
    district: "Netrokona",
    thana: "Netrokona Sadar",
    name: "Mi Store Netrokona (DTL)",
    address: "126, Chutto Bazar,Netrokona Sadar, Netrokona",
    contract: "01322877276",
  },
  {
    id: 48,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rangpur",
    district: "Dinajpur",
    thana: "Sader",
    name: "Mi Store Dinajpur",
    address: "Goneshtola Modarn Sader Dinajpur",
    contract: "01708813775",
  },
  {
    id: 49,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rajshahi",
    district: "Pabna",
    thana: "Ishwardi",
    name: "Mi Store Ishwardi",
    address: "Khan Market, Station Road, Ishwardi ,Pabna",
    contract: "01708813743",
  },
  {
    id: 50,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rangpur",
    district: "Rangpur",
    thana: "Rangpur Sadar",
    name: "Mi Store Rangpur (DTL)",
    address:
      "Shop No: 204 & 205, 1st Floor, Zila Parishad Super Market, Rangpur",
    contract: "01335248554",
  },
  {
    id: 51,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rangpur",
    district: "Nilphamari",
    thana: "Saidpur",
    name: "Mi Store Saidpur",
    address: "Shop No 187,Shahid Dr.Zikrul Haque Road,Saidpur",
    contract: "01708813721",
  },
  {
    id: 52,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rajshahi",
    district: "Rajshahi",
    thana: "Boalia,Rajshahi",
    name: "Mi Store Rajshahi",
    address: "G#84,Station Raod,Gowrhanga,New Market,Rajshahi",
    contract: "01708464122",
  },
  {
    id: 53,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rangpur",
    district: "Gaibandha",
    thana: "Gaibandha sador",
    name: "Mi Store Gaibandha DTL",
    address: "Circular Road, Gaibandha Sadar",
    contract: "01708813795",
  },
  {
    id: 54,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rajshahi",
    district: "Rajshahi",
    thana: "Boalia, Rajshahi",
    name: "Mi Home, DTL, Rajshahi",
    address: "Shop#15,Level 5,Theme Omar Plaza,Gourhanga,Rajshahi",
    contract: "01708813787",
  },
  {
    id: 55,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rajshahi",
    district: "Bogra",
    thana: "Bogra Sador",
    name: "Mi Store Bogra",
    address: "Shop: 23, Level-5, Runner Plaza , Nowabbari Road,Bogra.",
    contract: "01708464130",
  },
  {
    id: 56,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Rajshahi",
    district: "Naogaon",
    thana: "Sadar",
    name: "Mi Store Naogaon (DTL)",
    address: "Sarisha Hatir More, Main Road, Naogaon",
    contract: "01708813741",
  },
  {
    id: 57,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "Barisal",
    thana: "Kotwali",
    name: "Mi Store, Barisal (DTL)",
    address: "Fatema center, Sadar Road Barishal",
    contract: "01708813780",
  },
  {
    id: 58,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "Barisal",
    thana: "Kotwali",
    name: "Mi Store, SEBL 16, Barisal",
    address: "Kakolir More Barishal Sador, Barishal",
    contract: "01313027163",
  },
  {
    id: 59,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "patuakhali",
    thana: "patuakhali sadar",
    name: "Mi Store, Patuakhali (DTL)",
    address: "BRAC Bank Opposite, Natun Bazar, Sadar Road, Patuakhali",
    contract: "01708813792",
  },
  {
    id: 60,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Rajbari",
    thana: "Rajbari sadar",
    name: "Mi Store, Rajbari (DTL)",
    address: "Sadar Road, Pouro New market, Panna chottor Rajbari",
    contract: "01708813729",
  },
  {
    id: 61,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Faridpur",
    thana: "Faridpur Sadar",
    name: "Mi Store Faridpur (DTL)",
    address: "Shop #07, Shyamoli pouro super Marker, Jonotar mor, Faridpur",
    contract: "01730399135",
  },
  {
    id: 62,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Faridpur",
    thana: "Faridpur Sadar",
    name: "Mi Store Faridpur-3, DTL",
    address:
      "Shop # 05,Ground floor,Shamsuddin Market,Faridpur sadar, Faridpur",
    contract: "01313027142",
  },
  {
    id: 63,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "Pirojpur",
    thana: "Pirojpur Sadar",
    name: "Mi Store,Pirojpur SEBL-21",
    address: "Zila Parishad Market, Post Office Road",
    contract: "01313027168",
  },
  {
    id: 64,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Madaripur",
    thana: "Madaripur Sador",
    name: "Mi Store Madaripur (DTL)",
    address: "Juwel Chowdhury Plaza, Raintreetola, Puran Bazer, Madaripur",
    contract: "01708813777",
  },
  {
    id: 65,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Bagerhat",
    thana: "Bagerhat Sadar",
    name: "Mi Store, Bagerhat (DTL)",
    address:
      "Shop No-02, Alamin Market, Rail Road,Bagerhat(Opposite Sonali Bank PLC)",
    contract: "01708813754",
  },
  {
    id: 66,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "Bhola",
    thana: "Bhola Sadar",
    name: "Mi Store, Bhola (DTL)",
    address: "402 Sikander complex, Sadar road, bhola",
    contract: "01708813785",
  },
  {
    id: 67,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Madaripur",
    thana: "Rajoir",
    name: "Mi Store Takerhat (DTL)",
    address: "Abdul Aziz Complex Bank Road, Tekerhat Bazer, Rajoir,Madaripur",
    contract: "01322877285",
  },
  {
    id: 68,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Dhaka",
    district: "Shariatpur",
    thana: "Palong",
    name: "Mi Store, Shariatpur (DTL)",
    address: "Samim Plaza, Palong utthar bazar,",
    contract: "01708813769",
  },
  {
    id: 69,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Barisal",
    district: "Barguna",
    thana: "Barguna Sadar",
    name: "Mi Store, Barguna, DTL",
    address: "A Ali Bhaban, Holding-119, Road No-18, Sador Road, Barguna.",
    contract: "01730399125",
  },
  {
    id: 70,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "jessore",
    thana: "Abhainagor",
    name: "Mi Store, Noapara (DTL)",
    address: "Shop#01, Noapara Bazar, MianRoad,Noapara, jessore",
    contract: "01708813794",
  },
  {
    id: 71,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Khulna",
    thana: "Sonadanga",
    name: "Mi Store SEBL-26 (Shibbari More, Khulna)",
    address: "02 KDA Avenue,Shibbari More Khulna",
    contract: "01708813748",
  },
  {
    id: 72,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Kushtia",
    thana: "Kushtia Sadar",
    name: "Mi Store, Kushtia (DTL)",
    address: "#276,Rojob Ali Market N.S Road,Kushtia",
    contract: "01708813745",
  },
  {
    id: 73,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Jhenaidah",
    thana: "Jhenaidah Sadar",
    name: "Mi Store, Jhenaidah (DTL)",
    address:
      "Shop No#3, Zilla Porisod Super Market,Infornt of Govt. K.C Collage,Jhenaidah",
    contract: "01708813793",
  },
  {
    id: 74,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Jashore",
    thana: "Jashore Sador",
    name: "Mi Store, SEBL 5, Jessore-1",
    address: "102,103 Kashem Tower Netazi Shuvash Chandra Bashu Road,Jashore.",
    contract: "01713123963",
  },
  {
    id: 75,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Magura",
    thana: "Magura Sadar",
    name: "Mi Store, SEBL 10, Magura",
    address: "Holding, #New-175, #Old-34, MR Road Magura",
    contract: "01713123965",
  },
  {
    id: 76,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Khulna",
    thana: "Sonadanga",
    name: "Mi Home, DTL, Khulna",
    address: "18 KDA Avenue Khulna besides Sheikhpara",
    contract: "01708813742",
  },
  {
    id: 77,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Kushtia",
    thana: "Kushtia Sadar",
    name: "Mi Store, SEBL 17, Kushtia",
    address: "Shop-29 Tomij Uddin Market N S Road Kushtia.",
    contract: "01708813752",
  },
  {
    id: 78,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Jhenaidah",
    thana: "Jhenaidah Sadar",
    name: "Mi Store Jhenaidah-2 (DTL)",
    address: "shop #01,Munshi Market,Payra Cattar,Jhenaidah",
    contract: "01730399153",
  },
  {
    id: 79,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Shatkhira",
    thana: "Shatkhira Sadar",
    name: "Mi Store Shatkhira (DTL)",
    address: "Abul kashem sarak kaligonj highway road",
    contract: "01730399119",
  },
  {
    id: 80,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Meherpur",
    thana: "Meherpur Sadar",
    name: "Mi Store, Meherpur, DTL",
    address:
      "Shop#01,Holding#975/1, Main Road, Kashari Bazar, Meherpur Sadar Meherpur",
    contract: "01708813703",
  },
  {
    id: 81,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Chuadanga",
    thana: "Chuadanga",
    name: "Mi Store Chuadanga (DTL)",
    address: "Shop#6-7, Sayeed Mansio,Sahid Abul Khasem Road,Chuadanga",
    contract: "01730399163",
  },
  {
    id: 82,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Narail",
    thana: "Narail Sadar",
    name: "Mi Store, SEBL 6, Narail",
    address: "Shop No.29 Sadar Hospital Market,Narail",
    contract: "01713123966",
  },
  {
    id: 83,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Shatkhira",
    thana: "Shatkhira Sadar",
    name: "Mi Store, Shatkhira-2 (DTL)",
    address: "Shop No-112 & 113, Dacher Mia Tower, Sangitar More Sathkhira",
    contract: "01730399143",
  },
  {
    id: 84,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Khulna",
    district: "Khulna",
    thana: "Daulatpur Sadar",
    name: "Mi Store Daulatpur, Khulna-DX",
    address: "Shop No-08, Century Plaza, Daulatpur, Khulna",
    contract: "01730399158",
  },
  {
    id: 85,
    brand: "xiaomi",
    storeType: "Exclusive Xiaomi Store",
    division: "Sylhet",
    district: "Sunamganj",
    thana: "Sunamganj Sadar",
    name: "Mi Store Sunamgonj",
    address: "Shop No# 6, City Bhaban, Traffic Point, Sunamganj",
    contract: "01708813797",
  },
  {
    id: 86,
    brand: "honor",
    storeType: "Exclusive Honor Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "HONOR Brand Shop",
    address: "Shop-53, Basement-1 Basundhara City",
    contract: "01335248551",
  },
  {
    id: 87,
    brand: "honor",
    storeType: "Exclusive Honor Store",
    division: "Rangpur",
    district: "Dinajpur",
    thana: "Dinajpur Sadar",
    name: "HONOR Brand Shop",
    address: "Shop-2, Gonesh Tola, Planet Plaza, Dinajpur",
    contract: "01730399139",
  },
  {
    id: 88,
    brand: "honor",
    storeType: "Exclusive Honor Store",
    division: "Rangpur",
    district: "Kurigram",
    thana: "Kurigram Sadar",
    name: "HONOR Brand Shop",
    address: "Holding No-1799, Sarder Garden City, Ghoshpara, Kurigram",
    contract: "01322877223",
  },
  {
    id: 89,
    brand: "honor",
    storeType: "Exclusive Honor Store",
    division: "Dhaka",
    district: "Rajbari",
    thana: "Pangsha",
    name: "HONOR Brand Shop",
    address: "Kazi Super Market, Station Road, Pangsha, Rajbari.",
    contract: "01730399131",
  },
  {
    id: 90,
    brand: "honor",
    storeType: "Exclusive Honor Store",
    division: "Barisal",
    district: "Patuakhali",
    thana: "Patuakhali Sadar",
    name: "HONOR Brand Shop",
    address: "Honor BS, Notun Bazar, Sador Road, Patuakhali",
    contract: "01730399150",
  },
  {
    id: 91,
    brand: "infinix",
    storeType: "Exclusive Infinix Store",
    division: "Khulna",
    district: "Jessore",
    thana: "Jessore Sadar",
    name: "Infinix Brand Shop",
    address: "Ismail Bhaban, Garikhana Road, Jashore",
    contract: "01730399149",
  },
  {
    id: 92,
    brand: "infinix",
    storeType: "Exclusive Infinix Store",
    division: "Khulna",
    district: "Kushtia",
    thana: "Kushtia Sadar",
    name: "Infinix Brand Shop",
    address: "151/3, Moula Bhaban, NS Road, Kushtia",
    contract: "01730399155",
  },
  {
    id: 93,
    brand: "infinix",
    storeType: "Exclusive Infinix Store",
    division: "Rajshahi",
    district: "Rajshahi",
    thana: "Rajshahi Sadar",
    name: "Infinix Brand Shop",
    address: "Shop No-12, A H Tower, Alangkar More, Rajshahi",
    contract: "01335248553",
  },
  {
    id: 94,
    brand: "realme",
    storeType: "Exclusive Realme Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Gulshan",
    name: "Realme Brand Shop",
    address:
      "Shop-523, Level-4, Police Plaza Concord Shopping Mall, Gulshan-1, Dhaka-1212",
    contract: "01335248550",
  },
  {
    id: 95,
    brand: "realme",
    storeType: "Exclusive Realme Store",
    division: "Dhaka",
    district: "Madaripur",
    thana: "Rajoir",
    name: "Realme Brand Shop",
    address: "Kachabazar Road,Takerhat,Madaripur.",
    contract: "01322877203",
  },
  {
    id: 96,
    brand: "tecno",
    storeType: "Exclusive Tecno Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "TECNO Brand Shop",
    address: "Shop-50, Basement-1, Bashundhara City Shopping Mall",
    contract: "01335248552",
  },
  {
    id: 97,
    brand: "huawei",
    storeType: "Exclusive Huawei Store",
    division: "Dhaka",
    district: "Dhaka",
    thana: "Tejgaon",
    name: "HUAWEI Experience Store",
    address: "Basement-1, Bashundhara City",
    contract: "01335248557",
  },
  {
    id: 98,
    brand: "huawei",
    storeType: "Exclusive Huawei Store",
    division: "Chattogram",
    district: "Chattogram",
    thana: "Agrabad",
    name: "HUAWEI Experience Store",
    address: "Shop #503 (4th Floor), Akhtaruzzaman Center, Agrabad Chattogram",
    contract: "01335248559",
  },
];
